// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC25cSUWk1bCG0kyAZcjOdxd9Q1uINinDk',
    appId: '1:958420746280:web:4ae8159a752ebde0f9751d',
    messagingSenderId: '958420746280',
    projectId: 'skywise-climate',
    authDomain: 'skywise-climate.firebaseapp.com',
    storageBucket: 'skywise-climate.firebasestorage.app',
    measurementId: 'G-9S5E2WYJ0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEsVhATe4nfTnxZayhn1Ha7I7eg9Rd218',
    appId: '1:958420746280:android:75fcc2788e167520f9751d',
    messagingSenderId: '958420746280',
    projectId: 'skywise-climate',
    storageBucket: 'skywise-climate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMAKIhafO1lGpSJxI-r3JqfF6qtzE0lMQ',
    appId: '1:958420746280:ios:661957f1b859829cf9751d',
    messagingSenderId: '958420746280',
    projectId: 'skywise-climate',
    storageBucket: 'skywise-climate.firebasestorage.app',
    iosClientId: '958420746280-opjlv6isiqsqg0v1cfkkmt8mru8pmh8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.skywise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMAKIhafO1lGpSJxI-r3JqfF6qtzE0lMQ',
    appId: '1:958420746280:ios:661957f1b859829cf9751d',
    messagingSenderId: '958420746280',
    projectId: 'skywise-climate',
    storageBucket: 'skywise-climate.firebasestorage.app',
    iosClientId: '958420746280-opjlv6isiqsqg0v1cfkkmt8mru8pmh8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.skywise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC25cSUWk1bCG0kyAZcjOdxd9Q1uINinDk',
    appId: '1:958420746280:web:4535d6efa0c64702f9751d',
    messagingSenderId: '958420746280',
    projectId: 'skywise-climate',
    authDomain: 'skywise-climate.firebaseapp.com',
    storageBucket: 'skywise-climate.firebasestorage.app',
    measurementId: 'G-CQ4PL7FE8V',
  );
}
